# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_server_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(661, 579)
        self.pushOk = QtWidgets.QPushButton(Dialog)
        self.pushOk.setGeometry(QtCore.QRect(300, 540, 84, 25))
        self.pushOk.setObjectName("pushOk")
        self.pushExit = QtWidgets.QPushButton(Dialog)
        self.pushExit.setGeometry(QtCore.QRect(560, 540, 84, 25))
        self.pushExit.setObjectName("pushExit")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(60, 51, 256, 461))
        self.listWidget.setObjectName("listWidget")
        self.pushStart = QtWidgets.QPushButton(Dialog)
        self.pushStart.setGeometry(QtCore.QRect(410, 170, 181, 121))
        self.pushStart.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushOk.setText(_translate("Dialog", "PushButton"))
        self.pushExit.setText(_translate("Dialog", "Выход"))
        self.pushStart.setText(_translate("Dialog", "СТАРТ СЕРВЕР"))
